objects/Position__c.object
<CustomObject>
    <description>This object stores information about the open job
positions at our company.</description>
    <fields>
        <fullName>FunctionalArea__c</fullName>
        <label>FunctionalArea</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>HumanResources</fullName>
                </value>
                <value>
                    <fullName>InformationTechnology</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>RetailOperations</fullName>
                </value>
                <value>
                    <fullName>Warehousing</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/updateFunctionalArea.cls
public class updateFunctionalArea implements Database.Batchable<SObject>{
      public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, FunctionalArea__c FROM Position__c');
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        list<Position__c>positiontoUpdate=(list<Position__c>)scope;
        for(Position__c po : positiontoUpdate) {
            if(Position__c.FunctionalArea__c==Null){
                 po.FunctionalArea__c = 'Others';
              }
            else{}
        }
        update positiontoUpdate;
    }

    public void finish(Database.BatchableContext bc) {
        // Optional post-processing logic
    }
}